export const Candicates = [
  {
    name: 'Kübra ALBAYRAK',
    location: 'Atakum, Samsun',
    sex: 'Kadın',
    age: 37,
    current: 'Çalışıyor',
    date: '07 Mart 2024',
    status: 'İncelendi',
    education: 'Kasiyer aşçı yardımcı',
    school: 'Aöl.',
    graduate: 'Lise',
    job: 'Kasiyer',
    company: 'Popayes',
    finishAndEndDate: 'Eylül 2021 / Eylül 2022',
  },
  {
    name: 'Melek KILIÇ',
    location: 'Canik, Samsun',
    sex: 'Kadın',
    age: 39,
    current: 'Çalışmıyor',
    date: '04 Mart 2024',
    status: 'İncelendi',
    education: 'Mutfak Elemanı',
    school: 'Melahat Okulu',
    graduate: 'İlköğretim',
    job: 'Yönetici Asistanı',
    company: 'Coldwell Banker Park',
    finishAndEndDate: 'Nisan 2021 / Temmuz 2023',
  },
];
